version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - testpackage
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cirocosta/drwho
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
