builds:
  - binary: monero
    main: ./cmd/monero
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    tags:
      - osusergo
      - netgo
      - static_build
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"
